# Model arguments
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: openai/gsm8k
dataset_config: main
dataset_num_proc: 8
completion_only_loss: true

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: steps
eval_steps: 5
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-3B-SFT
hub_strategy: every_save
learning_rate: 3.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_length: 1024
max_steps: -1
num_train_epochs: 1
output_dir: data/Qwen2.5-3B-SFT
overwrite_output_dir: true
per_device_eval_batch_size: 64
per_device_train_batch_size: 32
push_to_hub: false
report_to:
- wandb
save_strategy: "steps"
save_steps: 100
save_total_limit: 1
seed: 42
use_liger_kernel: false
warmup_ratio: 0.05
eval_on_start: true